// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_getSha256 from './routes/api/getSha256.ts';
import * as $api_getSha384 from './routes/api/getSha384.ts';
import * as $api_getSha512 from './routes/api/getSha512.ts';
import * as $api_help from './routes/api/help.ts';
import * as $function_algorithm_getSecureHashAlgorithm from './routes/function/algorithm/getSecureHashAlgorithm.tsx';
import * as $function_creation_calcBeatsPerMinute from './routes/function/creation/calcBeatsPerMinute.tsx';
import * as $index from './routes/index.tsx';
import * as $info from './routes/info.tsx';
import * as $note_post_ from './routes/note/[...post].tsx';
import * as $profile from './routes/profile.tsx';
import * as $sample from './routes/sample.tsx';
import * as $system_joke_delete from './routes/system/joke/delete.tsx';
import * as $system_joke_deleteHandler from './routes/system/joke/deleteHandler.ts';
import * as $system_joke_edit from './routes/system/joke/edit.tsx';
import * as $system_joke_editHandler from './routes/system/joke/editHandler.ts';
import * as $system_joke_index from './routes/system/joke/index.tsx';
import * as $system_joke_indexHandler from './routes/system/joke/indexHandler.ts';
import * as $system_joke_post_jokeId_ from './routes/system/joke/post/[jokeId].tsx';
import * as $system_peak_delete from './routes/system/peak/delete.tsx';
import * as $system_peak_edit from './routes/system/peak/edit.tsx';
import * as $system_peak_index from './routes/system/peak/index.tsx';
import * as $system_peak_post_private_delete from './routes/system/peak/post/private/delete.tsx';
import * as $system_peak_post_private_edit from './routes/system/peak/post/private/edit.tsx';
import * as $system_peak_post_public_delete from './routes/system/peak/post/public/delete.tsx';
import * as $system_peak_post_public_edit from './routes/system/peak/post/public/edit.tsx';
import * as $system_peak_room_private_roomId_ from './routes/system/peak/room/private/[roomId].tsx';
import * as $system_peak_room_public_roomId_ from './routes/system/peak/room/public/[roomId].tsx';
import * as $template from './routes/template.tsx';
import * as $terms from './routes/terms.tsx';
import * as $work_post_ from './routes/work/[...post].tsx';
import * as $Function_CalcBeatsPerMinute_CalcBeatsPerMinute from './islands/Function/CalcBeatsPerMinute/CalcBeatsPerMinute.tsx';
import * as $Function_CalcBeatsPerMinute_MultiTimeInput from './islands/Function/CalcBeatsPerMinute/MultiTimeInput.tsx';
import * as $Function_CalcBeatsPerMinute_MultiTimeOutput from './islands/Function/CalcBeatsPerMinute/MultiTimeOutput.tsx';
import * as $Function_CalcBeatsPerMinute_MultiTimeTypeSelect from './islands/Function/CalcBeatsPerMinute/MultiTimeTypeSelect.tsx';
import * as $Function_GetSecureHashAlgorithm_GetSecureHashAlgorithm from './islands/Function/GetSecureHashAlgorithm/GetSecureHashAlgorithm.tsx';
import * as $Joke_PostEditor from './islands/Joke/PostEditor.tsx';
import * as $Original_Frame_Board from './islands/Original/Frame/Board.tsx';
import * as $Original_Frame_Frame from './islands/Original/Frame/Frame.tsx';
import * as $Original_Frame_FrameFunction from './islands/Original/Frame/FrameFunction.tsx';
import * as $Original_Frame_FrameObject from './islands/Original/Frame/FrameObject.tsx';
import * as $Original_Frame_Mode from './islands/Original/Frame/Mode.tsx';
import * as $Original_Info from './islands/Original/Info.tsx';
import * as $Original_Menu from './islands/Original/Menu.tsx';
import * as $Original_Miscellaneous_FileUploader from './islands/Original/Miscellaneous/FileUploader.tsx';
import * as $Original_Miscellaneous_MultilingualContent from './islands/Original/Miscellaneous/MultilingualContent.tsx';
import * as $Original_Miscellaneous_MultilingualContentSwitcher from './islands/Original/Miscellaneous/MultilingualContentSwitcher.tsx';
import * as $Original_Miscellaneous_ResultFieldset from './islands/Original/Miscellaneous/ResultFieldset.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
    routes: {
        './routes/_404.tsx': $_404,
        './routes/_app.tsx': $_app,
        './routes/api/getSha256.ts': $api_getSha256,
        './routes/api/getSha384.ts': $api_getSha384,
        './routes/api/getSha512.ts': $api_getSha512,
        './routes/api/help.ts': $api_help,
        './routes/function/algorithm/getSecureHashAlgorithm.tsx': $function_algorithm_getSecureHashAlgorithm,
        './routes/function/creation/calcBeatsPerMinute.tsx': $function_creation_calcBeatsPerMinute,
        './routes/index.tsx': $index,
        './routes/info.tsx': $info,
        './routes/note/[...post].tsx': $note_post_,
        './routes/profile.tsx': $profile,
        './routes/sample.tsx': $sample,
        './routes/system/joke/delete.tsx': $system_joke_delete,
        './routes/system/joke/deleteHandler.ts': $system_joke_deleteHandler,
        './routes/system/joke/edit.tsx': $system_joke_edit,
        './routes/system/joke/editHandler.ts': $system_joke_editHandler,
        './routes/system/joke/index.tsx': $system_joke_index,
        './routes/system/joke/indexHandler.ts': $system_joke_indexHandler,
        './routes/system/joke/post/[jokeId].tsx': $system_joke_post_jokeId_,
        './routes/system/peak/delete.tsx': $system_peak_delete,
        './routes/system/peak/edit.tsx': $system_peak_edit,
        './routes/system/peak/index.tsx': $system_peak_index,
        './routes/system/peak/post/private/delete.tsx': $system_peak_post_private_delete,
        './routes/system/peak/post/private/edit.tsx': $system_peak_post_private_edit,
        './routes/system/peak/post/public/delete.tsx': $system_peak_post_public_delete,
        './routes/system/peak/post/public/edit.tsx': $system_peak_post_public_edit,
        './routes/system/peak/room/private/[roomId].tsx': $system_peak_room_private_roomId_,
        './routes/system/peak/room/public/[roomId].tsx': $system_peak_room_public_roomId_,
        './routes/template.tsx': $template,
        './routes/terms.tsx': $terms,
        './routes/work/[...post].tsx': $work_post_,
    },
    islands: {
        './islands/Function/CalcBeatsPerMinute/CalcBeatsPerMinute.tsx': $Function_CalcBeatsPerMinute_CalcBeatsPerMinute,
        './islands/Function/CalcBeatsPerMinute/MultiTimeInput.tsx': $Function_CalcBeatsPerMinute_MultiTimeInput,
        './islands/Function/CalcBeatsPerMinute/MultiTimeOutput.tsx': $Function_CalcBeatsPerMinute_MultiTimeOutput,
        './islands/Function/CalcBeatsPerMinute/MultiTimeTypeSelect.tsx': $Function_CalcBeatsPerMinute_MultiTimeTypeSelect,
        './islands/Function/GetSecureHashAlgorithm/GetSecureHashAlgorithm.tsx': $Function_GetSecureHashAlgorithm_GetSecureHashAlgorithm,
        './islands/Joke/PostEditor.tsx': $Joke_PostEditor,
        './islands/Original/Frame/Board.tsx': $Original_Frame_Board,
        './islands/Original/Frame/Frame.tsx': $Original_Frame_Frame,
        './islands/Original/Frame/FrameFunction.tsx': $Original_Frame_FrameFunction,
        './islands/Original/Frame/FrameObject.tsx': $Original_Frame_FrameObject,
        './islands/Original/Frame/Mode.tsx': $Original_Frame_Mode,
        './islands/Original/Info.tsx': $Original_Info,
        './islands/Original/Menu.tsx': $Original_Menu,
        './islands/Original/Miscellaneous/FileUploader.tsx': $Original_Miscellaneous_FileUploader,
        './islands/Original/Miscellaneous/MultilingualContent.tsx': $Original_Miscellaneous_MultilingualContent,
        './islands/Original/Miscellaneous/MultilingualContentSwitcher.tsx': $Original_Miscellaneous_MultilingualContentSwitcher,
        './islands/Original/Miscellaneous/ResultFieldset.tsx': $Original_Miscellaneous_ResultFieldset,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
